module.exports = {
 GET_RESTAURANTS: 'GET_RESTAURANTS',
 GET_RESTAURANTS_SUCCESS: 'GET_RESTAURANTS_SUCCESS',
 SORT_RESTAURANTS: 'SORT_RESTAURANTS',
 FILTER_RESTAURANTS: 'FILTER_RESTAURANTS',
 UPDATE_SUGGESTIONS: 'UPDATE_SUGGESTIONS',
 TOGGLE_OVERLAY: 'TOGGLE_OVERLAY',
 REMOVE_FILTER: 'REMOVE_FILTER',
 GET_RECENT_SEARCHES: 'GET_RECENT_SEARCHES',
 UPDATE_RECENT_SEARCHES: 'UPDATE_RECENT_SEARCHES',
 UPDATE_RECENT_SEARCHES_SESSION: 'UPDATE_RECENT_SEARCHES_SESSION'
};
